package com.sunbeam;

public enum MenuEnums {
	EXIT, ADDBOOK,DISPLAYBOOKINFORWARDORDER,SEARCHBOOKWITHISBN,DELETEBOOKFORGIVENINDEX,DELETEBOOKFORGIVENID,DELETEBOOKFORGIVENNAME,
	SORTBOOKBYISBNASCORDER,SORTBOOKBYPRICEDEXCORDER,REVERSELIST,DEFAULTVALUE;
}
